version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: jakarta.platform:jakarta.jakartaee-api
    versions:
    - 9.0.0
  - dependency-name: org.liquibase:liquibase-core
    versions:
    - 4.3.3
  - dependency-name: org.apache.poi:poi-ooxml
    versions:
    - 4.1.2
    - 5.0.0
  - dependency-name: org.apache.poi:poi
    versions:
    - 4.1.2
    - 5.0.0
  - dependency-name: net.bull.javamelody:javamelody-core
    versions:
    - 1.86.0
    - 1.87.0
  - dependency-name: org.apache.maven.plugins:maven-compiler-plugin
    versions:
    - 3.8.1-jboss-2
  - dependency-name: org.yaml:snakeyaml
    versions:
    - "1.27"
    - "1.28"
  - dependency-name: org.jacoco:jacoco-maven-plugin
    versions:
    - 0.8.6
  - dependency-name: org.postgresql:postgresql
    versions:
    - 42.2.18
    - 42.2.19
  - dependency-name: org.jboss.logmanager:jboss-logmanager
    versions:
    - 2.1.18.Final
  - dependency-name: org.junit.jupiter:junit-jupiter-engine
    versions:
    - 5.7.0
  - dependency-name: org.junit.jupiter:junit-jupiter-api
    versions:
    - 5.7.0
  - dependency-name: org.apache.maven.plugins:maven-surefire-plugin
    versions:
    - 3.0.0-M5
  - dependency-name: com.lowagie:itext
    versions:
    - 4.2.1
