language: java

jdk:
- oraclejdk8

before_install:
- openssl aes-256-cbc -K $encrypted_01cb97b32830_key -iv $encrypted_01cb97b32830_iv
  -in .travis/deploy.key.enc -out .travis/deploy.key -d
  
after_success:
  - ./deploy.sh
