language: java
jdk:
- oraclejdk11
before_install:
- openssl aes-256-cbc -K $encrypted_20c4e0acc5aa_key -iv $encrypted_20c4e0acc5aa_iv
  -in deploy.key.enc -out deploy.key -d
- chmod +x deploy.sh
after_success:
- "./deploy/deploy.sh"
