language: java

jdk:
  - oraclejdk8
  
script: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

deploy:
  - provider: heroku
    api_key:
      secure: GWIf0fU3vRnpny99oWPxjLjEVpaBymlz4lCQm5kR9Mdpv0if5pRjSGDeJgqiZxsj3Zdk+cy2ESDKo5IXQ06BIvK9r/gxWir8ATvNyHre5cn3HaT8u9nInChfJJoWk/26SlTdFiCpa+Wyn9ls4rbY9mkGHFk8jWq9npywlhLl0Lfs2U3yP/UsUKBCkwHV2bwZdXMSDe3ETZqM1pIae3WAzaWT/ksmGLgAd7i/3Hq7zaGSCDv6xhAI6nzdGvp4emiFau0lBmfEosQN0DVg7BML6hfSDKr91OnmZB/6/oLzqGKUbBLNt2HAHVrj6d9R4ueFqgEnDY8AX2bH0Ehu58Rtg5cyaM/9y2uC68elvUfVf0mXeArPC+YXdEJeX46eJYWfCYEHB2pZYl85stM2PaCVrM491jB0D1hpPg9Hg4Sb6WcPka41wN9VydJGtM1HeQ9SegzyT20zlAx3mOETGAlrWlM5642ZcdEvgR+xNhqoU/tAlkeid3TGVmPuDSPIGEPxLyqfdkVjLRuak9K7thzV2SguFb9yMU1t0c/J7mZrlYeF1Kitx3oRApqzVVS3RRM28DGTcZXBnGgoJZoKwPFB9y65eqZ5aLq/ZTi3Lu/1QwVMPvWbSY/G6v9035VQa/7ybQYMKa/v3PQBo08NzQLqZchPqVWHNVb1hOlwYbQwTRE=
    app: famivac-gestionnaire-int
    on:
      repo: paoesco/famivac-gestionnaire
      branch: development
  - provider: heroku
    api_key:
      secure: Lm7dkqXTROQXiF0JVHREvD3UyVFMxEYfj7S3teuvX5pB5GRIGfWh6PUZ/UiqAGQ6nmYgZWSpVFofw0L+zGaXnPwtSCR0K+lH3AX/YbxxbVzT2gFvVRty5WCu/JiSkRFDe8G8RbNp5j3wDZqBnwWO0EH+Xjb15WjWXLd6EZr15r+QrpUFyzmLcPLRi/5C55qPyQxZHp9gsYZKNjb/mVlaZqSkvZ4QjSYp73kCzD99jiqoT1LPUtHUbM6ArsOAO3OF9Z8ndUZz86rF/WHUgHI/t5x9K5t5q68TCL8Dtu0jsJmRNdIOpZAd1V4i8zHXEG7ob8TSw/6tpkIsq/VXkyUNJbjwMU/CW+R9IjEx9lnTvTdNdrb1VMcO2tNQ1EBVKT6t76Jf+FvAkMGdOcOA8VJwXb07hBlzZKZZtF+91kzHXYwTnZcj4r1kDSUj3XDRzC1edDbb+Gd5d+S89DwOyDOVJY6sW7s3TYUctlc41pdmW5Zu5joZQSR1BhYM6ESiKXP+qJN+uYFa42pkkZ0/RuqFqzr6E/uQSqDMz+IQ0uCRD7HHdknbzsgKhTDOI14I2lofLNNph7VD8ALegS2OEj5Gf3TxpNgxfuXJGYTEJcOS5V5JlwgYjRGMvbT/SSWX/FbVpcDT2ea6dt9Dr03Y2b3wofAqAfHnTnxNlFlH9YEFR6U=
    app: famivac-gestionnaire-prod
    on:
      repo: paoesco/famivac-gestionnaire
      branch: master
