language: java
jdk:
- oraclejdk8
deploy:
  provider: heroku
  api_key:
    secure: GWIf0fU3vRnpny99oWPxjLjEVpaBymlz4lCQm5kR9Mdpv0if5pRjSGDeJgqiZxsj3Zdk+cy2ESDKo5IXQ06BIvK9r/gxWir8ATvNyHre5cn3HaT8u9nInChfJJoWk/26SlTdFiCpa+Wyn9ls4rbY9mkGHFk8jWq9npywlhLl0Lfs2U3yP/UsUKBCkwHV2bwZdXMSDe3ETZqM1pIae3WAzaWT/ksmGLgAd7i/3Hq7zaGSCDv6xhAI6nzdGvp4emiFau0lBmfEosQN0DVg7BML6hfSDKr91OnmZB/6/oLzqGKUbBLNt2HAHVrj6d9R4ueFqgEnDY8AX2bH0Ehu58Rtg5cyaM/9y2uC68elvUfVf0mXeArPC+YXdEJeX46eJYWfCYEHB2pZYl85stM2PaCVrM491jB0D1hpPg9Hg4Sb6WcPka41wN9VydJGtM1HeQ9SegzyT20zlAx3mOETGAlrWlM5642ZcdEvgR+xNhqoU/tAlkeid3TGVmPuDSPIGEPxLyqfdkVjLRuak9K7thzV2SguFb9yMU1t0c/J7mZrlYeF1Kitx3oRApqzVVS3RRM28DGTcZXBnGgoJZoKwPFB9y65eqZ5aLq/ZTi3Lu/1QwVMPvWbSY/G6v9035VQa/7ybQYMKa/v3PQBo08NzQLqZchPqVWHNVb1hOlwYbQwTRE=
  app: famivac-gestionnaire-int
  on:
    repo: paoesco/famivac-gestionnaire
    branch: development
